[package]
name = "duchess-java-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
duchess = { path = "../.." }
thiserror = "1.0.40"

[dev-dependencies]
ui_test = "0.17.0"

[build_dependencies]
walkdir = "2.3"

[[test]]
name = "ui"
harness = false
